### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by ShuaikangXie** [minhaolee/2D3DMATR#6]
When I ran CUDA_VISIBLE_DEVICES=0 python trainval.py, the following error occurred

Namespace()
Traceback (most recent call last):
  File "trainval.py", line 60, in <module>
    main()
  File "trainval.py", line 55, in main
    trainer = Trainer(cfg)
  File "trainval.py", line 14, in __init__
    super().__init__(cfg)
  File "/root/autodl-tmp/vision3d-main/vision3d/engine/epoch_based_trainer.py", line 35, in __init__
    super().__init__(cfg)
  File "/root/autodl-tmp/vision3d-main/vision3d/engine/base_trainer.py", line 76, in __init__
    self._debug_mode = self._args.debug
AttributeError: 'Namespace' object has no attribute 'debug'

It seems that the parameters were not loaded...

**Comment by zhongxingjian0914** [comment]
Have you solved it yet？

**Comment by shibing15** [comment]
> Have you solved it yet？
I think it can be solved by following:
in trainval.py 
  from vision3d.utils.parser import add_trainer_args
  before: cfg = make_cfg()
  should have: add_trainer_args()

**Comment by zhongxingjian0914** [comment]
thank you

---- Replied Message ----
| From | Yunda ***@***.***> |
| Date | 04/25/2024 20:47 |
| To | minhaolee/2D3DMATR ***@***.***> |
| Cc | zhongxingjian0914 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [minhaolee/2D3DMATR] runtime error (Issue #6) |

Have you solved it yet？
I think it can be solved by following:
in trainval.py
from vision3d.utils.parser import add_trainer_args
before: cfg = make_cfg()
should have: add_trainer_args()

**Comment by zhongxingjian0914** [comment]
Permission denied: '/workspace/vision3d-output/2d3dmatr.7scenes.stage4.level3.stage1/logs/train-20240428-143726.log
How to solve the virtual environment permission problem in Ubuntu？
